### ISSUE TITLE
needs more state machines

### ISSUE THREAD

**Issue by a-johnston** [gleichsnerd/saabbingo#1]
we need to look at the content of the flip flop

**Comment by gleichsnerd** [comment]
Billions and billions of state machines

**Comment by a-johnston** [comment]
have you ever looked in carnegie mellon? all state machines

**Comment by gleichsnerd** [comment]
Contacted carnegie mellon, borrowed a couple billion state machines and a pair of flip flops.

**Comment by gleichsnerd** [comment]
Forgot to write 0 to memory

**Comment by gleichsnerd** [comment]
Update is live, can confirm has flip-flops
